### ISSUE TITLE
async `reactor.run_once` do not stop while using async-http-faraday as faraday adapter to make http call

### ISSUE THREAD

**Issue by leomao10** [socketry/async-http-faraday#14]
Hi @ioquatix ,

I just tried to play around this gem after the video you posted on youtube:
https://www.youtube.com/watch?v=uU8ziRoJ2Z8&feature=youtu.be
And I want to give `async` a try after watching it, and I came up with following code in `test_async.rb`:

```ruby
#!/usr/bin/env ruby
require 'async'
require 'faraday'
require 'async/http/faraday'

module TestAsync
  URL = 'https://www.google.com/search'
  TOPICS = %W{ruby python lisp javascript cobol}

  def self.fetch_topics_async
    Async.logger.debug!
    Async::Reactor.run do
      Faraday.get "#{URL}/?ruby"
    end
  end
end

Faraday.default_adapter = :async_http
TestAsync.fetch_topics_async
```
And this code doesn't stop until I get bored and interrupt it. If I use `net_http` as faraday adapter instead of `async_http`, I can see it would finish in less than 1s.

Not sure if that would help but here is the output I got with debug logs:
```
 0.12s    debug: Async::Pool::Controller [oid=0x3ff1938e816c] [pid=34237] [2020-03-27 00:06:37 +1100]
               | No resources resources, allocating new one...
 0.12s    debug: Async::HTTP::Client [oid=0x3ff1938e8234] [pid=34237] [2020-03-27 00:06:37 +1100]
               | Making connection to #<Async::HTTP::Endpoint https://www.google.com/search/?ruby {}>
 0.14s    debug: Async::IO::Socket [pid=34237] [2020-03-27 00:06:37 +1100]
               | Connecting to #<Addrinfo: 216.58.203.100:443 TCP (www.google.com)>
 0.14s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:06:37 +1100]
               | @ready = [] @running = []
 0.14s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:06:37 +1100]
               | Selecting with 1 children with interval = infinite...
 0.16s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:06:37 +1100]
               | @ready = [] @running = []
 0.16s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:06:37 +1100]
               | Selecting with 1 children with interval = infinite...
 0.27s    debug: Async::HTTP::Protocol::HTTPS [pid=34237] [2020-03-27 00:06:37 +1100]
               | Negotiating protocol "h2"...
 0.27s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:06:37 +1100]
               | @ready = [#<Fiber:0x00007fe3271c9460@/usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-1.24.2/lib/async/task.rb:254 (suspended)>] @running = []
 0.27s    debug: Async::IO::Stream [oid=0x3ff19411d300] [pid=34237] [2020-03-27 00:06:37 +1100]
               | Draining 1 writes (51 bytes)...
 0.27s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:06:37 +1100]
               | Selecting with 1 children with interval = 0...
 0.27s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:06:37 +1100]
               | @ready = [#<Fiber:0x00007fe3271c9460@/usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-1.24.2/lib/async/task.rb:254 (suspended)>] @running = []
 0.27s    debug: Async::IO::Stream [oid=0x3ff19411d300] [pid=34237] [2020-03-27 00:06:37 +1100]
               | Draining 1 writes (13 bytes)...
 0.27s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:06:37 +1100]
               | Selecting with 1 children with interval = infinite...
 0.28s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:06:37 +1100]
               | @ready = [#<Fiber:0x00007fe3271c9460@/usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-1.24.2/lib/async/task.rb:254 (suspended)>] @running = []
 0.28s    debug: Async::IO::Stream [oid=0x3ff19411d300] [pid=34237] [2020-03-27 00:06:37 +1100]
               | Draining 1 writes (9 bytes)...
 0.29s    debug: Async::Pool::Controller [oid=0x3ff1938e816c] [pid=34237] [2020-03-27 00:06:37 +1100]
               | Wait for resource -> #<Async::HTTP::Protocol::HTTP2::Client 0 active streams>
 0.29s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:06:37 +1100]
               | Selecting with 1 children with interval = 0...
 0.29s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:06:37 +1100]
               | @ready = [#<Fiber:0x00007fe3271c9460@/usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-1.24.2/lib/async/task.rb:254 (suspended)>] @running = []
 0.29s    debug: Async::IO::Stream [oid=0x3ff19411d300] [pid=34237] [2020-03-27 00:06:37 +1100]
               | Draining 1 writes (49 bytes)...
 0.29s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:06:37 +1100]
               | Selecting with 1 children with interval = 0...
 0.29s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:06:37 +1100]
               | @ready = [#<Fiber:0x00007fe328884998@/usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-1.24.2/lib/async/task.rb:254 (suspended)>] @running = []
 0.29s    debug: Async::IO::Stream [oid=0x3ff19411d300] [pid=34237] [2020-03-27 00:06:37 +1100]
               | Draining 1 writes (9 bytes)...
 0.29s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:06:37 +1100]
               | Selecting with 1 children with interval = infinite...
 0.39s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:06:37 +1100]
               | @ready = [#<struct Async::Notification::Signal waiting=[#<Fiber:0x00007fe3271c9460@/usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-1.24.2/lib/async/task.rb:254 (suspended)>], value=nil>] @running = []
 0.39s    debug: Async::Pool::Controller [oid=0x3ff1938e816c] [pid=34237] [2020-03-27 00:06:37 +1100]
               | Reuse #<Async::HTTP::Protocol::HTTP2::Client 0 active streams>
 0.39s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:06:37 +1100]
               | Selecting with 1 children with interval = infinite...
 0.39s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:06:37 +1100]
               | @ready = [#<Fiber:0x00007fe327840ca8@/usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-1.24.2/lib/async/task.rb:254 (suspended)>] @running = []
 0.39s    debug: Async::IO::Stream [oid=0x3ff19411d300] [pid=34237] [2020-03-27 00:06:37 +1100]
               | Draining 1 writes (17 bytes)...
 0.39s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:06:37 +1100]
               | Selecting with 1 children with interval = infinite...
  1m0s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:07:37 +1100]
               | @ready = [] @running = []
  1m0s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:07:37 +1100]
               | Selecting with 1 children with interval = infinite...
^C 1m55s    debug: Async::Reactor [oid=0x3ff1938e4c60] [pid=34237] [2020-03-27 00:08:32 +1100]
               | Exiting run-loop because .
Traceback (most recent call last):
	5: from test_async.rb:20:in `<main>'
	4: from test_async.rb:13:in `fetch_topics_async'
	3: from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-1.24.2/lib/async/reactor.rb:56:in `run'
	2: from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-1.24.2/lib/async/reactor.rb:234:in `run'
	1: from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-1.24.2/lib/async/reactor.rb:204:in `run_once'
/usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-1.24.2/lib/async/reactor.rb:204:in `select': Interrupt
```

## Ruby version
Tested in both 2.6.5 & 2.7.0

**Comment by ioquatix** [comment]
The reason why this happens is because of an issue between async-http and faraday which isn't quite resolved yet.

The main point is, `async-http` is using HTTP/2 and creating a persistent connection which is used for all 5 requests. The persistent connection creates a background task, and so the reactor will never exit. In essence, you need to add `Faraday.default_connection.close` somewhere.

Here is the full example, based on your original code: https://github.com/socketry/async-http-faraday/blob/master/examples/topics.rb

**Comment by leomao10** [comment]
Thanks for the quick response, do you think it is worth to add that in example in `readme`?

**Comment by ioquatix** [comment]
Sure can you make a PR?

**Comment by leomao10** [comment]
Sure, will do
